### ISSUE TITLE
False positive for relative json link

### ISSUE THREAD

**Issue by vscaiceanu-1a** [UmbrellaDocs/linkspector#12]
We have a relative link to a `json` file in our `md` and linkspector finds it as invalid.
```shell
$ linkspector check
🚫 apps/github-cascading-app/README.md, ./schemas/config.schema.json, 404, 34, Cannot find: ./schemas/config.schema.json.
❌ Error: Some links in the specified files are not valid.
```

The link works well, you can find it here: https://github.com/AmadeusITGroup/otter/blob/main/apps/github-cascading-app/README.md

`markdown-link-check` finds it valid.

```shell
FILE: apps/github-cascading-app/README.md
  [✓] https://github.com/apps/otter-cascading
  [✓] ./schemas/config.schema.json

  2 links checked.

```

**Comment by gaurav-nelson** [comment]
@vscaiceanu-1a Thank you for creating this issue. Currently, Linkspector only checks for hyperlinks, and link to a local file should have been skipped. I plan to implement local link checking sometime.
