### ISSUE TITLE
Allow linkspector to be ran without a configuration file

### ISSUE THREAD

**Issue by hugobuddel** [UmbrellaDocs/linkspector#13]
Perhaps it would be useful to allow linkspector to be ran without a configuration file.

There are two ways to this:
- Use some defaults, e.g. `dirs: .` to mimic the behavior of markdown-link-checker
- Allow some configuration to be set as command line parameters.

We currently added the following line to [our github action](https://github.com/AstarVienna/DevOps/pull/9/files) for smooth transition from markdown-link-checker:
```bash
        # Generate default configuration file if it doesn't exist.
        if [ ! -f .linkspector.yml ] ; then printf "dirs:\n  - ./\n" > .linkspector.yml ; fi
```
While this works, it looks a bit ugly.

FWIW, we cannot use markdown-link-checker anymore, as SPIE uses a new redirection scheme in which working urls like https://doi.org/10.1117/12.2559784 are marked as broken by markdown-link-checker. linkspector correctly identifies them as working. So this seemed like a good moment to switch to linkspector.

And thanks for your work!

**Comment by gaurav-nelson** [comment]
Thank you @hugobuddel Seems a like a good suggestion. I'll add this one.
