### ISSUE TITLE
Ignoring aliveStatusCodes

### ISSUE THREAD

**Issue by CsatariGergely** [UmbrellaDocs/linkspector#16]
Hi, thanks for this very usefull utility. I'm in the process of building it to the GitHub workflow for the Nephio open source project. 
For some of the links I got a 304, what I think is still okay and should be considered as alive. I've added a config file and added 304 to the aliveStatusCodes section, but those links are still treated as error: 
![image](https://github.com/UmbrellaDocs/linkspector/assets/11458775/d58bb7d4-adf2-466a-9730-473378ff0022)

**Comment by gaurav-nelson** [comment]
@CsatariGergely Thank you for creating the issue. Can you share more info about the screenshot? Did you run it as a GitHub action?

**Comment by CsatariGergely** [comment]
Thanks for the fix. 
Yes, I'm using linkspector from a GitHub action: https://github.com/nokia/nephio-docs/blob/add-linkcheck/.github/workflows/check-links-md.yml

**Comment by CsatariGergely** [comment]
@gaurav-nelson sorry I have a similar issue, but I'm not sure if this is a bug. 
I've set up a rule to ignore localhost links, but it seems that the config is either wrong or ignored:
![image](https://github.com/UmbrellaDocs/linkspector/assets/11458775/6e22f1e0-afee-42fc-a4b4-99543298237f)
