### ISSUE TITLE
baseURL vs baseUrl

### ISSUE THREAD

**Issue by bmuenzenmeyer** [UmbrellaDocs/linkspector#20]
This library is exactly what I was looking for, thanks so far!

---

I'm having trouble using `baseUrl` in the config.

Docs: `baseUrl` https://github.com/UmbrellaDocs/linkspector?tab=readme-ov-file#base-url
Config Validator: `baseUrl` https://github.com/UmbrellaDocs/linkspector/blob/main/lib/validate-config.js#L25
Usage: `baseURL` [destructured](https://github.com/UmbrellaDocs/linkspector/blob/43c2afb664c2491755fd56017c8af73c4a765dae/lib/extract-markdown-hyperlinks.js#L21) off of config - https://github.com/UmbrellaDocs/linkspector/blob/43c2afb664c2491755fd56017c8af73c4a765dae/lib/extract-markdown-hyperlinks.js#L39

I think this mismatch is making it never be applied, right?

**Comment by gaurav-nelson** [comment]
@bmuenzenmeyer Thank you for creating a detailed issue. I've pushed a fix.
