### ISSUE TITLE
The repo uses pnpm, but github action uses npm

### ISSUE THREAD

**Issue by marcindulak** [UmbrellaDocs/linkspector#37]
https://github.com/UmbrellaDocs/linkspector/blob/5643ed77adc76da5537c3f5093a723c7d097876e/.github/workflows/npm-publish.yml#L19-L20

Since the [package-lock.json](https://docs.npmjs.com/cli/v10/configuring-npm/package-lock-json) is missing, the installation outcome of the github action workflow may be non-repeatable.

**Comment by gaurav-nelson** [comment]
✅ via #39
