### ISSUE TITLE
[BUG] Section links appear to be reported as broken when they are not

### ISSUE THREAD

**Issue by KStocky** [UmbrellaDocs/linkspector#57]
**Describe the bug**

Links to sections of the current page are reported as broken when they are valid.

**To Reproduce**

This is a [link](https://github.com/KStocky/ShaderTestFramework/actions/runs/9245090594) to a failing report of Linkspector that is run alongside [markdown link checker](https://github.com/gaurav-nelson/github-action-markdown-link-check?tab=readme-ov-file).

It claims that the link 4c of my [tutorial](https://github.com/KStocky/ShaderTestFramework/blob/LinkValidation/docs/Tutorial.md) is broken when it is demonstrably not.

[markdown link checker](https://github.com/gaurav-nelson/github-action-markdown-link-check?tab=readme-ov-file) succeeds in validating that it is correct.

**Expected behavior**
Expected a valid link to a page section to report as valid

**Comment by gaurav-nelson** [comment]
Thank you @KStocky for submitting the issue. It is a bug indeed. It's happening because the Linkspector is trying to match the id `#what-did-we-do-here` with `#what-did-we-do-here?` (with question mark) and failing. I'll get in a fix for this one.
