### ISSUE TITLE
[BUG] When checking markdown file some links have trailing period

### ISSUE THREAD

**Issue by theskillwithin** [UmbrellaDocs/linkspector#96]
When checking markdown files. get a lot of links with a trailing period when the check runs on them. however this trailing period does not exist in the markdown file itself

simple solution could be just to remove any trailing periods from the url string before testing

```
  message:"Cannot reach https://www.jogc.com/article/S1701-2163(16)39372-0/fulltext. Status: 403"  location:{path:"docs/resources/ailment_resources_links.md"  range:{start:{line:141  column:3}  end:{line:141  column:104}}}  severity:ERROR  source:{name:"linkspector"  url:"https://github.com/UmbrellaDocs/linkspector"}
  message:"Cannot reach https://www.cag-acg.org/images/publications/GERD_Consensus_Update_2004.pdf. Status: 404"  location:{path:"docs/resources/ailment_resources_links.md"  range:{start:{line:157  column:3}  end:{line:157  column:101}}}  severity:ERROR  source:{name:"linkspector"  url:"https://github.com/UmbrellaDocs/linkspector"}
  message:"Cannot reach https://www.pharmacists.ca/cpha-ca/assets/File/minorailments/GERD_En_FINAL.pdf. Status: 403"  location:{path:"docs/resources/ailment_resources_links.md"  range:{start:{line:161  column:3}  end:{line:161  column:96}}}  severity:ERROR  source:{name:"linkspector"  url:"https://github.com/UmbrellaDocs/linkspector"}
  ```
  

**To Reproduce**

Run through a markdown file with a lot of links

```md
- [SOGC on Emergency Contraception (2015)](https://www.jogc.com/article/S1701-2163(16)39372-0/fulltext)
```

**Comment by gaurav-nelson** [comment]
Thank you @theskillwithin for creating this issue. I was unable to reproduce this issue. Can you share a file or failed run if you have run it in an action?

**Comment by theskillwithin** [comment]
markdown: https://gist.github.com/theskillwithin/e08f0029acc5b6dded2cad1bcf73941c

action: https://gist.github.com/theskillwithin/7d081411aa7ef63c0abb11e8ee7df10f

**Comment by gaurav-nelson** [comment]
Well that `.` is not the part of the failed link but [the message Linkspector shows](https://github.com/UmbrellaDocs/linkspector/blob/main/index.js#L49). 

If you check the status it shows [403 which means server did not process the request](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/403). Which is common when using the GitHub action because they don't want too many bots to block the traffic.
